"""
Targeted unit tests for fix/canonical-hrf-sfreq (S4).

Scope:
- Canonical HRFs are now lazily generated by tree.get_canonical_hrf at the
  calling scan's sample rate and duration, instead of being eagerly
  constructed at a hardcoded 7.81 Hz / 30 s during the first tree.insert.
- tree.insert no longer creates a sentinel sibling at self.root.right;
  the first inserted node just becomes root with no children.
- tree.nearest_neighbor now returns (None, float("inf")) on miss instead
  of (self.root.right, float("inf")). Callers that want a canonical
  fallback must explicitly call get_canonical_hrf with their own sfreq.
- montage.estimate_activity, montage.localize_hrfs, and any other caller
  that needs a canonical now goes through the shared helper, so all
  canonical generation paths use the same scan-aware sample rate.

Fast, no fNIRS data files.
"""

import inspect
import pytest
import numpy as np


def _user_hrf(ch_name, x, y, z, oxygenation=True):
    from hrfunc.hrtree import HRF
    suffix = 'hbo' if oxygenation else 'hbr'
    return HRF(
        'doi',
        f'{ch_name}_{suffix}',
        30.0,
        7.81,
        np.ones(234),
        location=[x, y, z],
        estimates=[],
        locations=[],
    )


# ---------------------------------------------------------------------------
# tree.insert no longer creates a canonical sentinel
# ---------------------------------------------------------------------------

class TestInsertNoSentinel:
    def test_first_insert_root_has_no_right_child(self):
        from hrfunc.hrtree import tree
        t = tree()
        user = _user_hrf('s1_d1', 0.0, 0.0, 0.0)
        t.insert(user)
        assert t.root is user
        # Pre-S4: t.root.right was a canonical sentinel at [359, 359, 359]
        # Post-S4: t.root.right is None
        assert t.root.right is None
        assert t.root.left is None

    def test_tree_size_matches_user_inserts(self):
        """After three inserts, the tree should contain exactly three nodes
        (plus None children), not four with a canonical sentinel."""
        from hrfunc.hrtree import tree
        t = tree()
        nodes = [
            _user_hrf('a', 0.0, 0.0, 0.0),
            _user_hrf('b', 1.0, 0.0, 0.0),
            _user_hrf('c', -1.0, 0.0, 0.0),
        ]
        for n in nodes:
            t.insert(n)

        collected = []
        def walk(node):
            if node is None:
                return
            collected.append(node)
            walk(node.left)
            walk(node.right)
        walk(t.root)
        assert len(collected) == 3
        assert all(not n.ch_name.startswith('canonical') for n in collected)


# ---------------------------------------------------------------------------
# tree.get_canonical_hrf helper
# ---------------------------------------------------------------------------

class TestGetCanonicalHrf:
    def test_helper_exists(self):
        from hrfunc.hrtree import tree
        assert hasattr(tree, 'get_canonical_hrf')

    def test_hbo_kernel_length_matches_sfreq_times_duration(self):
        from hrfunc.hrtree import tree
        t = tree()
        node = t.get_canonical_hrf(oxygenation=True, sfreq=5.0, duration=30.0)
        # Glover HRF at t_r=0.2, time_length=30 should have ~150 samples
        assert 140 <= len(node.trace) <= 160

    def test_kernel_length_scales_with_sfreq(self):
        """Higher sfreq should produce a longer kernel for the same duration."""
        from hrfunc.hrtree import tree
        t = tree()
        low = t.get_canonical_hrf(oxygenation=True, sfreq=5.0, duration=30.0)
        high = t.get_canonical_hrf(oxygenation=True, sfreq=10.0, duration=30.0)
        assert len(high.trace) > len(low.trace)

    def test_hbr_is_negation_of_hbo(self):
        from hrfunc.hrtree import tree
        t = tree()
        hbo = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        hbr = t.get_canonical_hrf(oxygenation=False, sfreq=7.81, duration=30.0)
        assert np.allclose(hbr.trace, -hbo.trace)

    def test_cache_returns_same_object_on_second_call(self):
        from hrfunc.hrtree import tree
        t = tree()
        a = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        b = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        assert a is b

    def test_different_cache_keys_return_different_objects(self):
        from hrfunc.hrtree import tree
        t = tree()
        a = t.get_canonical_hrf(oxygenation=True, sfreq=5.0, duration=30.0)
        b = t.get_canonical_hrf(oxygenation=True, sfreq=10.0, duration=30.0)
        c = t.get_canonical_hrf(oxygenation=False, sfreq=5.0, duration=30.0)
        assert a is not b
        assert a is not c
        assert b is not c

    def test_canonical_node_has_method_canonical(self):
        from hrfunc.hrtree import tree
        t = tree()
        node = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        assert node.context['method'] == 'canonical'

    def test_canonical_node_uses_sentinel_location(self):
        from hrfunc.hrtree import tree
        t = tree()
        node = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        # The sentinel location is chosen to be far outside realistic
        # MNE head coordinates (meters, typically < 0.5)
        assert node.x >= 100
        assert node.y >= 100
        assert node.z >= 100

    def test_canonical_hbr_name_conventions(self):
        from hrfunc.hrtree import tree
        t = tree()
        hbo = t.get_canonical_hrf(oxygenation=True, sfreq=7.81, duration=30.0)
        hbr = t.get_canonical_hrf(oxygenation=False, sfreq=7.81, duration=30.0)
        assert 'canonical' in hbo.ch_name
        assert 'canonical' in hbr.ch_name
        assert hbo.oxygenation is True
        assert hbr.oxygenation is False


# ---------------------------------------------------------------------------
# nearest_neighbor fallback returns None on miss
# ---------------------------------------------------------------------------

class TestNearestNeighborFallback:
    def test_empty_tree_returns_none(self):
        from hrfunc.hrtree import tree
        t = tree()
        probe = _user_hrf('probe', 0.0, 0.0, 0.0)
        result, distance = t.nearest_neighbor(probe, max_distance=0.01)
        assert result is None
        assert distance == float('inf')

    def test_far_away_query_returns_none(self):
        from hrfunc.hrtree import tree
        t = tree()
        t.insert(_user_hrf('a', 0.0, 0.0, 0.0))
        far_probe = _user_hrf('probe', 100.0, 100.0, 100.0)
        result, distance = t.nearest_neighbor(far_probe, max_distance=0.01)
        assert result is None

    def test_source_no_longer_references_root_right_fallback(self):
        """Regression guard: _delete_recursive of this fallback path must
        not re-introduce a root.right reference that expects a canonical."""
        from hrfunc.hrtree import tree
        src = inspect.getsource(tree.nearest_neighbor)
        # The fallback must NOT read self.root.right as if it were canonical
        assert 'self.root.right' not in src


# ---------------------------------------------------------------------------
# montage integration: canonical branch uses the helper
# ---------------------------------------------------------------------------

class TestMontageCanonicalIntegration:
    def test_estimate_activity_source_uses_helper(self):
        """Regression guard: estimate_activity's canonical branch must use
        get_canonical_hrf, not read self.hbo_tree.root.right."""
        from hrfunc.hrfunc import montage
        src = inspect.getsource(montage.estimate_activity)
        assert 'get_canonical_hrf' in src
        # The old root.right fallback must be gone
        assert 'hbo_tree.root.right' not in src
        assert 'hbr_tree.root.right' not in src

    def test_localize_hrfs_source_uses_helper(self):
        """localize_hrfs should no longer inline its own glover_hrf call —
        it now goes through tree.get_canonical_hrf."""
        from hrfunc.hrfunc import montage
        src = inspect.getsource(montage.localize_hrfs)
        assert 'get_canonical_hrf' in src
        # Inline glover_hrf generation at the function level should be gone
        assert 'glover_hrf' not in src


# ---------------------------------------------------------------------------
# Round-trip: generate canonical at different sfreqs, verify distinct length
# ---------------------------------------------------------------------------

class TestCanonicalSfreqRoundTrip:
    def test_canonical_matches_scan_sfreq_not_hardcoded(self):
        """Pre-fix the canonical was locked to 7.81 Hz (t_r=0.128) regardless
        of the calling scan. Post-fix, generating at a different sfreq
        produces a kernel of a different length that matches that sfreq."""
        from hrfunc.hrtree import tree
        t = tree()
        at_781 = t.get_canonical_hrf(True, 7.81, 30.0)
        at_500 = t.get_canonical_hrf(True, 5.0, 30.0)
        at_1000 = t.get_canonical_hrf(True, 10.0, 30.0)

        # Lengths should be roughly sfreq * duration
        assert abs(len(at_781.trace) - 234) <= 10
        assert abs(len(at_500.trace) - 150) <= 10
        assert abs(len(at_1000.trace) - 300) <= 10

        # And they should be distinct objects
        assert at_781 is not at_500
        assert at_500 is not at_1000
